// Hand-written dictionary of real fruits (canonical names, lowercase).
// Includes botanical fruits (tomato, cucumber, avocado, peppers, squash, peas...).
// "apple" stays in the dictionary so it can be recognised — and rejected.

export const FRUITS: string[] = [
  "apple",
  "apricot",
  "avocado",
  "banana",
  "blackberry",
  "blueberry",
  "boysenberry",
  "cherry",
  "cranberry",
  "date",
  "dragonfruit",
  "durian",
  "elderberry",
  "fig",
  "grape",
  "grapefruit",
  "guava",
  "kiwi",
  "kumquat",
  "lemon",
  "lime",
  "lychee",
  "mango",
  "cantaloupe",
  "honeydew",
  "watermelon",
  "nectarine",
  "orange",
  "papaya",
  "passionfruit",
  "peach",
  "pear",
  "persimmon",
  "pineapple",
  "plum",
  "pomegranate",
  "pomelo",
  "quince",
  "raspberry",
  "strawberry",
  "tangerine",
  "clementine",
  "mandarin",
  "coconut",
  "olive",
  "tomato",
  "cucumber",
  "pepper",
  "chili",
  "pumpkin",
  "squash",
  "zucchini",
  "eggplant",
  "okra",
  "plantain",
  "breadfruit",
  "jackfruit",
  "starfruit",
  "rambutan",
  "mangosteen",
  "longan",
  "loquat",
  "medlar",
  "mulberry",
  "gooseberry",
  "huckleberry",
  "cloudberry",
  "bilberry",
  "feijoa",
  "cherimoya",
  "soursop",
  "sweetsop",
  "custard apple",
  "jabuticaba",
  "acai",
  "salak",
  "langsat",
  "santol",
  "sapodilla",
  "mamey",
  "tamarillo",
  "pepino",
  "goji",
  "goldenberry",
  "ground cherry",
  "yuzu",
  "citron",
  "calamansi",
  "tangelo",
  "bergamot",
  "finger lime",
  "kaffir lime",
  "greengage",
  "mirabelle",
  "damson",
  "sloe",
  "chokecherry",
  "jujube",
  "asian pear",
  "crabapple",
  "muscadine",
  "blackcurrant",
  "redcurrant",
  "whitecurrant",
  "currant",
  "juneberry",
  "chokeberry",
  "sea buckthorn",
  "rose hip",
  "hawthorn",
  "barberry",
  "bearberry",
  "lingonberry",
  "marionberry",
  "loganberry",
  "tayberry",
  "dewberry",
  "coffee",
  "cacao",
  "vanilla",
  "pea",
  "sweetcorn",
  "naranjilla",
  "cupuacu",
  "abiu",
  "canistel",
  "baobab",
  "marula",
  "kiwano",
  "surinam cherry",
  "pawpaw",
  "tamarind",
  "hog plum",
  "plumcot",
  "pluot",
  "aprium",
  "monstera",
  "noni",
  "ackee",
  "genip",
  "atemoya",
  "biriba",
  "ilama",
  "soncoya",
  "lucuma",
  "white sapote",
  "black sapote",
  "acerola",
  "nance",
  "grumichama",
  "camu camu",
  "blood orange",
  "bitter orange",
  "satsuma",
  "limequat",
  "sweet lime",
  "meyer lemon",
  "ugli",
  "red banana",
  "sea grape",
  "salmonberry",
  "thimbleberry",
  "wineberry",
  "crowberry",
  "casaba",
  "crenshaw",
  "canary melon",
  "santa claus melon",
  "rose apple",
  "wax apple",
  "prickly pear",
  "cornelian cherry",
  "miracle fruit",
  "cocoplum",
  "ambarella",
  "java plum",
  "malay apple",
  "green sapote",
  "bacuri",
  "mountain soursop",
  "pond apple",
  "ume",
  "nanking cherry",
  "beach cherry",
  "rowanberry",
  "highbush cranberry",
  "honeyberry",
  "salal",
  "buffaloberry",
  "nagoonberry",
  "olallieberry",
  "oroblanco",
  "dekopon",
  "ortanique",
  "tangor",
  "rangpur",
  "sudachi",
  "kabosu",
  "amanatsu",
  "akebi",
  "yumberry",
  "limeberry",
  "pin cherry",
];

// Alias (natural spelling) -> canonical name.
export const ALIASES: Record<string, string> = {
  // apple cultivars -> apple (recognised, then banned)
  "granny smith": "apple",
  gala: "apple",
  fuji: "apple",
  honeycrisp: "apple",
  "pink lady": "apple",
  "red delicious": "apple",
  "golden delicious": "apple",
  braeburn: "apple",
  mcintosh: "apple",
  jazz: "apple",
  envy: "apple",
  "cosmic crisp": "apple",
  cortland: "apple",
  jonagold: "apple",
  // kiwi
  kiwifruit: "kiwi",
  kivifruit: "kiwi",
  "chinese gooseberry": "kiwi",
  "baby kiwi": "kiwi",
  "hardy kiwi": "kiwi",
  "golden kiwi": "kiwi",
  // pineapple / mango / banana / citrus cultivars
  ananas: "pineapple",
  alphonso: "mango",
  ataulfo: "mango",
  cavendish: "banana",
  "ladyfinger banana": "banana",
  "blue java": "banana",
  "cooking banana": "plantain",
  "hass avocado": "avocado",
  concord: "grape",
  muscat: "grape",
  "cotton candy": "grape",
  "moon drop": "grape",
  scuppernong: "muscadine",
  "navel orange": "orange",
  "valencia orange": "orange",
  "cara cara": "orange",
  moro: "blood orange",
  tarocco: "blood orange",
  sanguinello: "blood orange",
  "seville orange": "bitter orange",
  "sour orange": "bitter orange",
  owari: "satsuma",
  kishu: "mandarin",
  murcott: "tangerine",
  "honey tangerine": "tangerine",
  clementina: "clementine",
  minneola: "tangelo",
  "ugly fruit": "ugli",
  "ugli fruit": "ugli",
  "jamaican tangelo": "ugli",
  "temple orange": "tangor",
  "rangpur lime": "rangpur",
  "sumo citrus": "dekopon",
  shiranui: "dekopon",
  sweetie: "oroblanco",
  "natsu mikan": "amanatsu",
  meyer: "meyer lemon",
  "sweet lemon": "sweet lime",
  kaffir: "kaffir lime",
  "makrut lime": "kaffir lime",
  "australian finger lime": "finger lime",
  calamondin: "calamansi",
  "philippine lime": "calamansi",
  "key lime": "lime",
  "persian lime": "lime",
  "eureka lemon": "lemon",
  "lisbon lemon": "lemon",
  etrog: "citron",
  bergamotte: "bergamot",
  pomello: "pomelo",
  pummelo: "pomelo",
  shaddock: "pomelo",
  "chinese grapefruit": "pomelo",
  "japanese citron": "yuzu",
  meiwa: "kumquat",
  nagami: "kumquat",
  // stone fruit
  "sour cherry": "cherry",
  "sweet cherry": "cherry",
  "bing cherry": "cherry",
  "rainier cherry": "cherry",
  morello: "cherry",
  griotte: "cherry",
  "pie cherry": "cherry",
  "wild cherry": "chokecherry",
  cornelian: "cornelian cherry",
  "downy cherry": "nanking cherry",
  "cedar bay cherry": "beach cherry",
  "fire cherry": "pin cherry",
  pitanga: "surinam cherry",
  surinam: "surinam cherry",
  "brazil cherry": "grumichama",
  grumixama: "grumichama",
  "donut peach": "peach",
  "flat peach": "peach",
  "saturn peach": "peach",
  "white peach": "peach",
  "yellow peach": "peach",
  "beach plum": "plum",
  "cherry plum": "plum",
  "reine claude": "greengage",
  "green plum": "greengage",
  "mirabelle plum": "mirabelle",
  "yellow plum": "mirabelle",
  bullace: "damson",
  "damson plum": "damson",
  "sloe berry": "sloe",
  blackthorn: "sloe",
  "japanese apricot": "ume",
  // pome fruit
  "siberian crabapple": "crabapple",
  nashi: "asian pear",
  "nashi pear": "asian pear",
  "japanese pear": "asian pear",
  "korean pear": "asian pear",
  "chinese pear": "asian pear",
  "apple pear": "asian pear",
  "sand pear": "asian pear",
  "ya pear": "asian pear",
  "ya li": "asian pear",
  "bartlett pear": "pear",
  "anjou pear": "pear",
  "bosc pear": "pear",
  "comice pear": "pear",
  "conference pear": "pear",
  "seckel pear": "pear",
  "williams pear": "pear",
  "flowering quince": "quince",
  "german medlar": "medlar",
  "dutch medlar": "medlar",
  "open arse": "medlar",
  "cactus pear": "prickly pear",
  "cactus fig": "prickly pear",
  tuna: "prickly pear",
  "tuna fruit": "prickly pear",
  "indian fig": "prickly pear",
  "barbary fig": "prickly pear",
  nopal: "prickly pear",
  // figs / dates / jujube
  "mission fig": "fig",
  "brown turkey fig": "fig",
  "kadota fig": "fig",
  "calimyrna fig": "fig",
  "adriatic fig": "fig",
  "black mission": "fig",
  "smyrna fig": "fig",
  "common fig": "fig",
  medjool: "date",
  "medjool date": "date",
  "deglet noor": "date",
  "deglet nour": "date",
  khajur: "date",
  rutab: "date",
  "barhi date": "date",
  ber: "jujube",
  "indian jujube": "jujube",
  "chinese date": "jujube",
  "red date": "jujube",
  "korean date": "jujube",
  "common jujube": "jujube",
  "japanese plum": "loquat",
  "japanese medlar": "loquat",
  "maltese plum": "loquat",
  pipa: "loquat",
  "bronze loquat": "loquat",
  // berries
  "himalayan blackberry": "blackberry",
  "lowbush blueberry": "blueberry",
  "highbush blueberry": "blueberry",
  "wild blueberry": "blueberry",
  "rabbiteye blueberry": "blueberry",
  whortleberry: "bilberry",
  blaeberry: "bilberry",
  hurtleberry: "bilberry",
  "european blueberry": "bilberry",
  "garden huckleberry": "huckleberry",
  "evergreen huckleberry": "huckleberry",
  "red huckleberry": "huckleberry",
  bakeapple: "cloudberry",
  knotberry: "cloudberry",
  "nordic berry": "cloudberry",
  "arctic bramble": "cloudberry",
  "dwarf raspberry": "cloudberry",
  "black raspberry": "raspberry",
  "golden raspberry": "raspberry",
  "arctic raspberry": "raspberry",
  "garden strawberry": "strawberry",
  "wild strawberry": "strawberry",
  "alpine strawberry": "strawberry",
  "beach strawberry": "strawberry",
  "musk strawberry": "strawberry",
  fraise: "strawberry",
  olallie: "olallieberry",
  serviceberry: "juneberry",
  saskatoon: "juneberry",
  shadbush: "juneberry",
  shadberry: "juneberry",
  "sugar plum": "juneberry",
  aronia: "chokeberry",
  "black chokeberry": "chokeberry",
  "zante currant": "currant",
  "dried currant": "currant",
  "champagne currant": "currant",
  cassis: "blackcurrant",
  "pink currant": "whitecurrant",
  cowberry: "lingonberry",
  foxberry: "lingonberry",
  "mountain cranberry": "lingonberry",
  "partridge berry": "lingonberry",
  "american cranberry": "cranberry",
  "european cranberry": "cranberry",
  "small cranberry": "cranberry",
  "southern mountain cranberry": "cranberry",
  bounceberry: "cranberry",
  "black crowberry": "crowberry",
  curlewberry: "crowberry",
  "japanese barberry": "barberry",
  zereshk: "barberry",
  "oregon grape": "barberry",
  kinnikinnick: "bearberry",
  mahonia: "barberry",
  agarita: "barberry",
  algerita: "barberry",
  "sea berry": "sea buckthorn",
  sandthorn: "sea buckthorn",
  "rose haw": "rose hip",
  "dog rose": "rose hip",
  haw: "hawthorn",
  "red haw": "hawthorn",
  "black haw": "hawthorn",
  mayhaw: "hawthorn",
  azarole: "hawthorn",
  "mediterranean medlar": "hawthorn",
  rowan: "rowanberry",
  "mountain ash": "rowanberry",
  "american cranberrybush": "highbush cranberry",
  "european cranberrybush": "highbush cranberry",
  "guelder rose": "highbush cranberry",
  "snowball bush": "highbush cranberry",
  haskap: "honeyberry",
  // melons
  rockmelon: "cantaloupe",
  melon: "cantaloupe",
  "musk melon": "cantaloupe",
  spanspek: "cantaloupe",
  "netted melon": "cantaloupe",
  "seedless watermelon": "watermelon",
  "piel de sapo": "santa claus melon",
  "christmas melon": "santa claus melon",
  "toad skin melon": "santa claus melon",
  // botanical vegetables-that-are-fruits
  "lemon cucumber": "cucumber",
  "armenian cucumber": "cucumber",
  "bell pepper": "pepper",
  "sweet pepper": "pepper",
  capsicum: "pepper",
  "black pepper": "pepper",
  chilli: "chili",
  "hot pepper": "chili",
  "cayenne pepper": "chili",
  jalapeno: "chili",
  "jalapeño": "chili",
  habanero: "chili",
  "ghost pepper": "chili",
  "grape tomato": "tomato",
  "beefsteak tomato": "tomato",
  "cherry tomato": "tomato",
  "plum tomato": "tomato",
  "heirloom tomato": "tomato",
  "love apple": "tomato",
  "tomatillo": "ground cherry",
  "mexican husk tomato": "ground cherry",
  "cape gooseberry": "goldenberry",
  "inca berry": "goldenberry",
  pichuberry: "goldenberry",
  physalis: "goldenberry",
  "husk cherry": "ground cherry",
  wolfberry: "goji",
  "matrimony vine": "goji",
  "tree tomato": "tamarillo",
  "dutch eggplant": "tamarillo",
  "melon pear": "pepino",
  lulo: "naranjilla",
  "little orange": "naranjilla",
  naranjillo: "naranjilla",
  crookneck: "squash",
  "butternut squash": "squash",
  "acorn squash": "squash",
  "winter squash": "squash",
  "summer squash": "squash",
  marrow: "squash",
  "bottle gourd": "squash",
  chayote: "squash",
  christophine: "squash",
  cushaw: "pumpkin",
  "field pumpkin": "pumpkin",
  "pumpkin squash": "pumpkin",
  courgette: "zucchini",
  "baby marrow": "zucchini",
  aubergine: "eggplant",
  brinjal: "eggplant",
  "garden egg": "eggplant",
  "lady finger": "okra",
  "ladies finger": "okra",
  gumbo: "okra",
  bhindi: "okra",
  "sweet pea": "pea",
  "green pea": "pea",
  "garden pea": "pea",
  "english pea": "pea",
  pease: "pea",
  mangetout: "pea",
  "snow pea": "pea",
  "sugar snap": "pea",
  corn: "sweetcorn",
  "corn on the cob": "sweetcorn",
  maize: "sweetcorn",
  "baby corn": "sweetcorn",
  "green olive": "olive",
  "black olive": "olive",
  "kalamata olive": "olive",
  kalamata: "olive",
  cocoanut: "coconut",
  "tender coconut": "coconut",
  "king coconut": "coconut",
  "beach grape": "sea grape",
  "bay grape": "sea grape",
  // tropicals
  pitaya: "dragonfruit",
  pitahaya: "dragonfruit",
  carambola: "starfruit",
  tarap: "breadfruit",
  marang: "breadfruit",
  breadnut: "breadfruit",
  "maya nut": "breadfruit",
  "ramon nut": "breadfruit",
  "seeded breadfruit": "breadfruit",
  "seedless breadfruit": "breadfruit",
  ulu: "breadfruit",
  cempedak: "jackfruit",
  champedak: "jackfruit",
  chempedak: "jackfruit",
  nangka: "jackfruit",
  kathal: "jackfruit",
  panasa: "jackfruit",
  "small jackfruit": "jackfruit",
  "wild jack": "jackfruit",
  "monkey jack": "jackfruit",
  lakoocha: "jackfruit",
  "monkey fruit": "jackfruit",
  jaca: "jackfruit",
  "monkey bread": "baobab",
  "upside down tree": "baobab",
  "cream of tartar tree": "baobab",
  "dead rat tree": "baobab",
  "bottle tree": "baobab",
  boab: "baobab",
  "jelly plum": "marula",
  morula: "marula",
  "cider tree": "marula",
  "elephant tree": "marula",
  "horned melon": "kiwano",
  "horned cucumber": "kiwano",
  "african horned cucumber": "kiwano",
  "jelly melon": "kiwano",
  "blowfish fruit": "kiwano",
  "spiked melon": "kiwano",
  "purple mangosteen": "mangosteen",
  "queen of fruits": "mangosteen",
  manggis: "mangosteen",
  "button mangosteen": "mangosteen",
  "yellow mangosteen": "mangosteen",
  "lemon drop mangosteen": "mangosteen",
  "seashore mangosteen": "mangosteen",
  "king of fruits": "durian",
  "civet fruit": "durian",
  duren: "durian",
  "red durian": "durian",
  "wild durian": "durian",
  guanabana: "soursop",
  graviola: "soursop",
  guanabano: "soursop",
  corossol: "soursop",
  "durian belanda": "soursop",
  rollinia: "biriba",
  "wild sugar apple": "biriba",
  "wild sweetsop": "biriba",
  "white annona": "ilama",
  papausa: "ilama",
  "cabeza de negro": "soncoya",
  "wild soursop": "mountain soursop",
  "alligator apple": "pond apple",
  chirimoya: "cherimoya",
  anona: "cherimoya",
  "anona cherimola": "cherimoya",
  "bullock heart": "custard apple",
  "bullocks heart": "custard apple",
  "sugar apple": "sweetsop",
  annona: "sweetsop",
  anon: "sweetsop",
  atis: "sweetsop",
  lanzones: "langsat",
  lansium: "langsat",
  duku: "langsat",
  kokosan: "langsat",
  pisitan: "langsat",
  "yellow langsat": "langsat",
  cottonfruit: "santol",
  kechapi: "santol",
  sentul: "santol",
  "yellow santol": "santol",
  "bangkok santol": "santol",
  "snake fruit": "salak",
  "salak fruit": "salak",
  salacca: "salak",
  "salak pondoh": "salak",
  "bali salak": "salak",
  "red salak": "salak",
  "white salak": "salak",
  rakum: "salak",
  "snakeskin fruit": "salak",
  "asam kelubi": "salak",
  "hairy lychee": "rambutan",
  nephelium: "rambutan",
  "wild rambutan": "rambutan",
  pulasan: "rambutan",
  "dragons eye": "longan",
  "kohala longan": "longan",
  "biew kiew": "longan",
  "diamond river": "longan",
  litchi: "lychee",
  lichi: "lychee",
  litchee: "lychee",
  leechee: "lychee",
  "alligator strawberry": "lychee",
  "common guava": "guava",
  "apple guava": "guava",
  "lemon guava": "guava",
  "strawberry guava": "guava",
  "cattley guava": "guava",
  "cherry guava": "guava",
  "pink guava": "guava",
  "white guava": "guava",
  guayaba: "guava",
  granadilla: "passionfruit",
  "sweet passionfruit": "passionfruit",
  lilikoi: "passionfruit",
  "pineapple guava": "feijoa",
  guavasteen: "feijoa",
  jaboticaba: "jabuticaba",
  "brazilian grape tree": "jabuticaba",
  cabeludinha: "jabuticaba",
  "yellow jabuticaba": "jabuticaba",
  "white jabuticaba": "jabuticaba",
  "west indian cherry": "acerola",
  "barbados cherry": "acerola",
  "golden spoon": "nance",
  "yellow cherry": "nance",
  hogberry: "nance",
  "savanna cherry": "nance",
  changunga: "nance",
  nanche: "nance",
  // sapote family and relatives
  "chocolate persimmon": "black sapote",
  "black persimmon": "black sapote",
  "chocolate pudding fruit": "black sapote",
  "zapote negro": "black sapote",
  "white sapota": "white sapote",
  casimiroa: "white sapote",
  "mexican apple": "white sapote",
  "zapote blanco": "white sapote",
  matasano: "white sapote",
  sapote: "white sapote",
  "mamey sapote": "mamey",
  "mamey colorado": "mamey",
  "red mamey": "mamey",
  mammee: "mamey",
  "mammee apple": "mamey",
  "south american apricot": "mamey",
  "santo domingo apricot": "mamey",
  abrico: "mamey",
  zapote: "mamey",
  "egg fruit": "canistel",
  "yellow sapote": "canistel",
  tiesa: "canistel",
  lamut: "canistel",
  nesberry: "sapodilla",
  noseberry: "sapodilla",
  mudapple: "sapodilla",
  sapota: "sapodilla",
  chiku: "sapodilla",
  chico: "sapodilla",
  "chico sapote": "sapodilla",
  naseberry: "sapodilla",
  soapapple: "sapodilla",
  dilly: "sapodilla",
  "star apple": "abiu",
  caimito: "abiu",
  "milk fruit": "abiu",
  "yellow star apple": "abiu",
  "caimito amarillo": "abiu",
  luma: "abiu",
  "sweet tamarind": "tamarind",
  "velvet tamarind": "tamarind",
  "indian date": "tamarind",
  "spanish lime": "genip",
  mamoncillo: "genip",
  quenepa: "genip",
  chenet: "genip",
  skinip: "genip",
  talisia: "genip",
  "spanish tamarind": "genip",
  "manila tamarind": "genip",
  "yellow mombin": "hog plum",
  "red mombin": "hog plum",
  "purple mombin": "hog plum",
  jocote: "hog plum",
  "spanish plum": "hog plum",
  "golden apple": "ambarella",
  "otaheite apple": "ambarella",
  "june plum": "ambarella",
  kedondong: "ambarella",
  jambolan: "java plum",
  jamun: "java plum",
  duhat: "java plum",
  lomboy: "java plum",
  "mountain apple": "malay apple",
  "ohia ai": "malay apple",
  pomerac: "malay apple",
  jambu: "rose apple",
  "java apple": "wax apple",
  "bell fruit": "wax apple",
  "watery rose apple": "wax apple",
  "water apple": "wax apple",
  macopa: "wax apple",
  tambis: "wax apple",
  "wax jambu": "wax apple",
  "white wax apple": "wax apple",
  "green wax apple": "wax apple",
  "black wax apple": "wax apple",
  "coco plum": "cocoplum",
  "paradise plum": "cocoplum",
  // odd edibles
  "miracle berry": "miracle fruit",
  "miraculous berry": "miracle fruit",
  "sweet berry": "miracle fruit",
  "magic fruit": "miracle fruit",
  "flavor berry": "miracle fruit",
  "monster fruit": "monstera",
  "monstera fruit": "monstera",
  "mexican breadfruit": "monstera",
  "fruit salad plant": "monstera",
  ceriman: "monstera",
  "window leaf": "monstera",
  "swiss cheese plant": "monstera",
  "cheese fruit": "noni",
  "indian mulberry": "noni",
  "beach mulberry": "noni",
  "vomit fruit": "noni",
  "dog dumpling": "noni",
  "rotten cheese fruit": "noni",
  "great morinda": "noni",
  achee: "ackee",
  "ackee apple": "ackee",
  "coffee cherry": "coffee",
  "coffee berry": "coffee",
  "arabica coffee": "coffee",
  "robusta coffee": "coffee",
  coffea: "coffee",
  liberica: "coffee",
  "cacao pod": "cacao",
  "chocolate berry": "cacao",
  "cocoa fruit": "cacao",
  "cocoa pod": "cacao",
  "cupu assu": "cupuacu",
  copoazu: "cupuacu",
  "brazilian cacao": "cupuacu",
  "vanilla bean": "vanilla",
  "vanilla pod": "vanilla",
  "vanilla orchid": "vanilla",
  kaki: "persimmon",
  "japanese persimmon": "persimmon",
  "oriental persimmon": "persimmon",
  "chinese persimmon": "persimmon",
  "american persimmon": "persimmon",
  "common persimmon": "persimmon",
  fuyu: "persimmon",
  "fuyu persimmon": "persimmon",
  hachiya: "persimmon",
  "sharon fruit": "persimmon",
  "date plum": "persimmon",
  mabolo: "persimmon",
  "velvet apple": "persimmon",
  "velvet persimmon": "persimmon",
  babaco: "papaya",
  "mountain papaya": "papaya",
  chamburo: "papaya",
  "tree melon": "papaya",
  "melon tree": "papaya",
  "melon papaw": "papaya",
  "fruta bomba": "papaya",
  lechosa: "papaya",
  mamon: "papaya",
  "american pawpaw": "pawpaw",
  "indiana banana": "pawpaw",
  "custard banana": "pawpaw",
  "chinese bayberry": "yumberry",
  "açaí": "acai",
  "acai berry": "acai",
};

// ---------- matching ----------

// Lowercase, trim, strip spaces/hyphens/apostrophes for lookup.
export function normalize(raw: string): string {
  return raw
    .normalize("NFKC")
    .toLowerCase()
    .trim()
    .replace(/[\s\-_'’.]/g, "");
}

function stripPlural(word: string): string | null {
  if (word.length > 4 && word.endsWith("ies")) return word.slice(0, -3) + "y";
  if (word.length > 4 && word.endsWith("oes")) return word.slice(0, -2);
  if (
    word.length > 5 &&
    (word.endsWith("ches") ||
      word.endsWith("shes") ||
      word.endsWith("xes") ||
      word.endsWith("sses") ||
      word.endsWith("zzes"))
  )
    return word.slice(0, -2);
  if (word.length > 3 && word.endsWith("s") && !word.endsWith("ss"))
    return word.slice(0, -1);
  return null;
}

// Levenshtein distance capped at max+1 (early exit).
function cappedDistance(a: string, b: string, max: number): number {
  if (Math.abs(a.length - b.length) > max) return max + 1;
  let prev = new Array<number>(b.length + 1);
  for (let j = 0; j <= b.length; j++) prev[j] = j;
  for (let i = 1; i <= a.length; i++) {
    let cur0 = i;
    let rowMin = cur0;
    let prevDiag = prev[0];
    prev[0] = i;
    for (let j = 1; j <= b.length; j++) {
      const temp = prev[j];
      const cost = a.charCodeAt(i - 1) === b.charCodeAt(j - 1) ? 0 : 1;
      const v = Math.min(prev[j] + 1, cur0 + 1, prevDiag + cost);
      prevDiag = temp;
      prev[j - 1] = cur0;
      cur0 = v;
      if (v < rowMin) rowMin = v;
    }
    prev[b.length] = cur0;
    if (rowMin > max) return max + 1;
  }
  return prev[b.length];
}

const fruitSet = new Map<string, string>();
for (const f of FRUITS) fruitSet.set(normalize(f), f);
const aliasMap = new Map<string, string>();
for (const [k, v] of Object.entries(ALIASES)) aliasMap.set(normalize(k), v);

// Canonical names + alias keys for typo matching (canonicals win ties).
const typoCandidates: { key: string; canonical: string; primary: boolean }[] = [
  ...FRUITS.map((f) => ({
    key: normalize(f),
    canonical: f,
    primary: true as boolean,
  })),
  ...[...aliasMap.entries()].map(([key, canonical]) => ({
    key,
    canonical,
    primary: false as boolean,
  })),
];

// Common vegetables and foods people might type. Genuinely not fruits, and
// some sit within typo distance of a real fruit (potato/tomato, kale/kaki),
// so they short-circuit to unknown before typo matching.
const NOT_FRUITS = new Set(
  [
    "rhubarb",
    "carrot",
    "potato",
    "sweet potato",
    "yam",
    "taro",
    "cassava",
    "yuca",
    "onion",
    "shallot",
    "leek",
    "chive",
    "garlic",
    "ginger",
    "lettuce",
    "arugula",
    "rocket",
    "endive",
    "radicchio",
    "watercress",
    "cabbage",
    "kale",
    "spinach",
    "broccoli",
    "cauliflower",
    "celery",
    "asparagus",
    "artichoke",
    "beet",
    "beetroot",
    "radish",
    "turnip",
    "parsnip",
    "swede",
    "rutabaga",
    "fennel",
    "mushroom",
    "brussels sprout",
    "jam",
    "jelly",
    "pie",
    "cake",
    "juice",
    "candy",
    "chocolate",
    "sugar",
    "salt",
    "salsa",
    "salad",
    "meat",
    "bread",
    "milk",
    "cheese",
    "fish",
    "egg",
    "beer",
    "ham",
  ].map(normalize),
);

// Returns the canonical fruit name, or null when unknown.
export function matchFruit(raw: string): string | null {
  const key = normalize(raw);
  if (!key) return null;
  const direct = fruitSet.get(key) ?? aliasMap.get(key);
  if (direct) return direct;
  const singular = stripPlural(key);
  if (singular) {
    const hit = fruitSet.get(singular) ?? aliasMap.get(singular);
    if (hit) return hit;
  }
  if (NOT_FRUITS.has(key)) return null;
  if (singular && NOT_FRUITS.has(singular)) return null;
  // Typo matching: short inputs are almost always jokes, not typos, and
  // real typos keep the first letter (kivi -> kiwi).
  if (key.length < 4) return null;
  let best: string | null = null;
  let bestDist = 3;
  let bestPrimary = false;
  for (const c of typoCandidates) {
    if (c.key[0] !== key[0]) continue;
    const d = cappedDistance(key, c.key, 2);
    if (
      d < bestDist ||
      (d === bestDist && c.primary && !bestPrimary && best !== null)
    ) {
      if (d > 2) continue;
      best = c.canonical;
      bestDist = d;
      bestPrimary = c.primary;
      if (d === 0) break;
    }
  }
  return bestDist <= 2 ? best : null;
}
